Fix compilation error when LOG_TAG is NULL
I get the following error when using android_testLog():

    packages/modules/NeuralNetworks/TypeUtils.h:206:28: error: indirection requires pointer operand ('long' invalid)
            android_testLog(_priority, LOG_TAG))                         \
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    system/logging/liblog/include/log/log_main.h:368:55: note: expanded from macro 'android_testLog'
      (__android_log_is_loggable_len(prio, tag, ((tag) && *(tag)) ? strlen(tag) : 0, \
                                                          ^~~~~~

Bug: N/A
Test: m
Change-Id: Ida6edbaf322473389e11ab81bf630d99c10e5e01